runtime: php
env: standard

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
- .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: 3MClJlJ8D3O9dIbPgt7wHaXIUp0iN96tC6xfCJPI+pQ=
  STORAGE_DIR: /tmp